### ISSUE TITLE
Have a thought for linting

### ISSUE THREAD

**Issue by AvDongle** [Uken81/Gurps-Character-Cheatsheet-Maker#41]
I noticed a bunch of code literacy related changes, have you looked into linting the project?

**Comment by Uken81** [comment]
Good spot.
I haven't got one installed but have had the thought that I need to start using one several times recently.

I'm installing and setting up Eslint now. Are there any others you would consider crucial?

I have also been thinking I need to start being more consistent with things like the order of imports and props, essentially grouping them. For example with imports I will have the react basics like useEffect, useState etc, followed by styles then component imports and finally third party libraries.  
Do you memorise patterns like these and try to be consistent or do you personalise your linter?
